Repository akiomik/seiun, pull requests merged in 2023-03, with the labels that each got.

#3 ログインとアカウント登録画面で入力欄が改行できてしまう問題の修正
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
Labels: bug

#5 fix: date formatting in FeedPost
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
Labels: bug

#9 Fix:投稿画面を開いた際にテキスト入力欄をフォーカスするように変更
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/NewPostForm.kt
Labels: enhancement

#10 Update:ログインと新規登録画面で入力欄を広げ、ボタンを右寄せに変更する
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
Labels: enhancement

#18 Add mute support
  .gitignore
  .idea/deploymentTargetDropDown.xml
  README.md
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/MuteInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/UnmuteInput.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/service/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/ConfirmDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/DeleteDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/MuteDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/ReportDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/TimelineScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#22 Add CustomApiResultConverterFactory
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/service/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/service/CustomApiResultConverterFactory.kt
  app/src/main/java/io/github/akiomik/seiun/service/UnitConverter.kt
Labels: enhancement

#21 Update dependencies
  app/build.gradle
  build.gradle
Labels: enhancement

#23 Use moshi-adapters
  app/build.gradle
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/Post.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostView.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/ReasonTrendOrReasonRepost.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/Repost.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationRecord.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/report/ReportCreateOutput.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/embed/EmbedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NoficationListItem.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
Labels: enhancement

#28 Add service provider support
  README.md
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/repository/ApplicationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/NotificationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/LoginViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/RegistrationViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#29 Use `by` for State
  app/src/main/java/io/github/akiomik/seiun/SeiunActivity.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/ReportDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NotificationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/NewPostFormModal.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/TimelineScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt
Labels: enhancement

#31 Add push notification
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/akiomik/seiun/NotificationWorker.kt
  app/src/main/java/io/github/akiomik/seiun/SeiunActivity.kt
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/Notification.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/UpdateNotificationSeenInput.kt
  app/src/main/java/io/github/akiomik/seiun/repository/ApplicationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/NotificationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/service/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NoficationListItem.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/theme/Color.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/NotificationViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#32 Refactor api
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/api/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/api/CustomApiResultConverterFactory.kt
  app/src/main/java/io/github/akiomik/seiun/api/ExpiredTokenException.kt
  app/src/main/java/io/github/akiomik/seiun/api/RequestHelper.kt
  app/src/main/java/io/github/akiomik/seiun/api/UnauthorizedException.kt
  app/src/main/java/io/github/akiomik/seiun/api/UnitConverter.kt
  app/src/main/java/io/github/akiomik/seiun/repository/ApplicationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/ApplicationViewModel.kt
Labels: enhancement

#33 Refactor datastore
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/datastores/Credential.kt
  app/src/main/java/io/github/akiomik/seiun/datastores/CredentialDataStore.kt
  app/src/main/java/io/github/akiomik/seiun/datastores/EncryptedDataStore.kt
  app/src/main/java/io/github/akiomik/seiun/datastores/Session.kt
  app/src/main/java/io/github/akiomik/seiun/datastores/SessionDataStore.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/ApplicationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/LoginViewModel.kt
Labels: enhancement

#34 Refactor auth
  app/src/main/java/io/github/akiomik/seiun/NotificationWorker.kt
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/api/RequestHelper.kt
  app/src/main/java/io/github/akiomik/seiun/repository/ApplicationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/AuthRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/NotificationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/ApplicationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/LoginViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/NotificationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/RegistrationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt
Labels: enhancement

#35 Drawer
  app/src/main/java/io/github/akiomik/seiun/SeiunActivity.kt
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/repository/ApplicationRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/App.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppBottomBar.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppDrawer.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppNavigation.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppScaffold.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppTopBar.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/AppViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/TimelineViewModel.kt
Labels: bug, enhancement

#37 Fix review issues
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/utilities/ServiceProviderValidator.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/LoginViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/RegistrationViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#38 Fix proguard
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/io/github/akiomik/seiun/api/AtpService.kt
Labels: bug

#40 Fix reply error
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
Labels: bug

#41 Fix drawer state
  app/src/main/java/io/github/akiomik/seiun/ui/app/App.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppNavigation.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodel/AppViewModel.kt
Labels: bug

#42 Use oss-lincenses-plugin
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppDrawer.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#47 Refactor viewmodels
  app/src/main/java/io/github/akiomik/seiun/ui/app/App.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppDrawer.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppNavigation.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppTopBar.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/DeleteDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/MuteDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/dialog/ReportDialog.kt
  app/src/main/java/io/github/akiomik/seiun/ui/login/LoginScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NotificationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/registration/RegistrationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/NewPostFormModal.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/TimelineScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/AppViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/ApplicationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/LoginViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/NotificationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/RegistrationViewModel.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/TimelineViewModel.kt
Labels: enhancement

#52 Refactor
  app/src/main/java/io/github/akiomik/seiun/SeiunApplication.kt
  app/src/main/java/io/github/akiomik/seiun/repository/PostFeedRepository.kt
  app/src/main/java/io/github/akiomik/seiun/repository/TimelineRepository.kt
  app/src/main/java/io/github/akiomik/seiun/utilities/UriConverter.kt
Labels: enhancement

#53 Add profile viewer for other users
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/feed/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserFeed.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserModal.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/UserFeedViewModel.kt
Labels: enhancement

#54 Use moshi-codegen
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/io/github/akiomik/seiun/model/AtpError.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/MyState.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/Profile.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/RefWithInfo.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/ViewerState.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/blob/UploadBlobOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/embed/External.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/embed/ExternalExternal.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/embed/Image.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/embed/PresentedExternal.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/embed/PresentedImage.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/AuthorFeed.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/FeedViewPost.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/FeedViewPostReplyRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/ImagesOrExternal.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/ImagesPresentedOrExternalPresented.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/Post.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostEntity.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostEntityTextSlice.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostReplyRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostView.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/PostViewViewerState.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/ReasonTrendOrReasonRepost.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/Repost.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/SetVoteInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/SetVoteOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/Timeline.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/feed/VoteDirection.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/MuteInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/UnmuteInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/Notification.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationList.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationRecord.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationSubject.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/UpdateNotificationSeenInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/report/RepoRefOrRecordRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/report/RepoRefOrStrongRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/report/ReportCreateInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/report/ReportCreateOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/system/DeclRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/account/AccountCreateInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/account/AccountCreateOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/repo/CreateRecordInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/repo/CreateRecordOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/repo/DeleteRecordInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/repo/StrongRef.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/session/SessionCreateInput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/session/SessionCreateOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/com/atproto/session/SessionRefreshOutput.kt
  app/src/main/java/io/github/akiomik/seiun/model/type/Image.kt
  build.gradle
Labels: enhancement

#55 Refactor build.grade dependencies
  app/build.gradle
  build.gradle
Labels: enhancement

#56 Use build.gradle.kts
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle
Labels: enhancement

#57 Add UserScreen
  app/src/main/java/io/github/akiomik/seiun/ui/app/App.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppBottomBar.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppDrawer.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppNavigation.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppScaffold.kt
  app/src/main/java/io/github/akiomik/seiun/ui/feed/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NoficationListItem.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NotificationScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/timeline/TimelineScreen.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserFeed.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/AppViewModel.kt
Labels: enhancement

#58 Improve user screen
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/AppViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#60 Follow
  README.md
  app/src/main/java/io/github/akiomik/seiun/api/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/Ref.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/Follow.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/UserFeedViewModel.kt
Labels: enhancement

#61 Official Gradle Wrapper Validation Action
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: enhancement

#65 Improve notification list components
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NoficationListItem.kt
Labels: enhancement

#67 Follows list
  app/src/main/java/io/github/akiomik/seiun/api/AtpService.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/actor/ViewerState.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/graph/Follows.kt
  app/src/main/java/io/github/akiomik/seiun/repository/UserRepository.kt
  app/src/main/java/io/github/akiomik/seiun/ui/app/AppNavigation.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/FeedLoadingIndicator.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/FollowsListModal.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/FollowsLoadingIndicator.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserFeed.kt
  app/src/main/java/io/github/akiomik/seiun/ui/user/UserScreen.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/FollowsViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#74 Fix notifications
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationRecord.kt
  app/src/main/java/io/github/akiomik/seiun/model/app/bsky/notification/NotificationSubject.kt
  app/src/main/java/io/github/akiomik/seiun/ui/feed/FeedPost.kt
  app/src/main/java/io/github/akiomik/seiun/ui/notification/NoficationListItem.kt
  app/src/main/java/io/github/akiomik/seiun/viewmodels/PostViewModel.kt
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug
